const getPlaybar = () => document.getElementsByTagName("ytmusic-player-bar")[0]

const getVideoPlayer = () => document.getElementsByTagName("ytmusic-player")[0]

const openInNewTab = () => window.open(document.URL.replace("music.youtube","www.youtube"), '_blank').focus()

function changeToURL(_ev) {
  if (!document.URL.startsWith("https://music.youtube.com/watch")) // open
    getPlaybar().click()
  openInNewTab()
}

function buildButton() {
  const likeButtonsAndSuchDiv = document.getElementsByClassName("middle-controls-buttons style-scope ytmusic-player-bar")[0]
  const menuButton = likeButtonsAndSuchDiv.getElementsByTagName("ytmusic-menu-renderer")[0].cloneNode()
  const svg = document.createElementNS('http://www.w3.org/2000/svg','svg');
  svg.setAttribute("xmlns","http://www.w3.org/2000/svg")
  svg.setAttribute("height","24" )
  svg.setAttribute("viewBox","0 0 24 24" )
  svg.setAttribute("width","24" )
  svg.setAttribute("focusable","false" )
  svg.setAttribute("aria-hidden","true" )
  svg.setAttribute("style","pointer-events: none; display: inherit; width: 100%; height: 100%;")

  // the following was autogenerated by gemini
  // 3. Create the outer group (yt-ringo2-red-svg_yt53) <g id="yt-ringo2-red-svg_yt53" transform="matrix(1, 0, 0, 1, -318.260895, -149.130432)">
  const mainGroup = document.createElementNS(svg, "g");
  mainGroup.setAttribute("id", "yt-ringo2-red-svg_yt53");
  mainGroup.setAttribute("transform", "matrix(1, 0, 0, 1, -318.260895, -149.130432)");

  // 4. Create the inner group for the logo shapes <g transform="matrix(1, 0, 0, 1, 535.869568, 244.860336)">
  const logoGroup = document.createElementNS(svgNS, "g");
  logoGroup.setAttribute("transform", "matrix(1, 0, 0, 1, 535.869568, 244.860336)");

  // 5. Create the Red Background Path// <path d="M14.4848 20C14.4848 20 23.5695 20 25.8229 19.4C27.0917 19.06 28.0459 18.08 28.3808 16.87C29 14.65 29 9.98 29 9.98C29 9.98 29 5.34 28.3808 3.14C28.0459 1.9 27.0917 0.94 25.8229 0.61C23.5695 0 14.4848 0 14.4848 0C14.4848 0 5.42037 0 3.17711 0.61C1.9286 0.94 0.954148 1.9 0.59888 3.14C0 5.34 0 9.98 0 9.98C0 9.98 0 14.65 0.59888 16.87C0.954148 18.08 1.9286 19.06 3.17711 19.4C5.42037 20 14.4848 20 14.4848 20Z" fill="#FF0033"></path>

  const bgPath = document.createElementNS(svgNS, "path");
  bgPath.setAttribute("d", "M14.4848 20C14.4848 20 23.5695 20 25.8229 19.4C27.0917 19.06 28.0459 18.08 28.3808 16.87C29 14.65 29 9.98 29 9.98C29 9.98 29 5.34 28.3808 3.14C28.0459 1.9 27.0917 0.94 25.8229 0.61C23.5695 0 14.4848 0 14.4848 0C14.4848 0 5.42037 0 3.17711 0.61C1.9286 0.94 0.954148 1.9 0.59888 3.14C0 5.34 0 9.98 0 9.98C0 9.98 0 14.65 0.59888 16.87C0.954148 18.08 1.9286 19.06 3.17711 19.4C5.42037 20 14.4848 20 14.4848 20Z");
  bgPath.setAttribute("fill", "#838383");

  // 6. Create the White Play Icon Path <path d="M19 10L11.5 5.75V14.25L19 10Z" fill="white"></path>
  const playPath = document.createElementNS(svgNS, "path");
  playPath.setAttribute("d", "M19 10L11.5 5.75V14.25L19 10Z");
  playPath.setAttribute("fill", "white");

  // 7. Create the empty placeholder group <g id="youtube-paths_yt53" transform="matrix(1, 0, 0, 1, 474.910889, 236.956528)"></g>
  const pathGroup = document.createElementNS(svgNS, "g");
  pathGroup.setAttribute("id", "youtube-paths_yt53");
  pathGroup.setAttribute("transform", "matrix(1, 0, 0, 1, 474.910889, 236.956528)");

  // 8. Assemble the tree
  logoGroup.appendChild(bgPath);
  logoGroup.appendChild(playPath);
  mainGroup.appendChild(logoGroup);
  mainGroup.appendChild(pathGroup);
  svg.appendChild(mainGroup);
  // gemini end

  const oldSvg = menuButton.getElementsByTagName("svg")
  menuButton.replaceChild(svg, oldSvg)
  menuButton.onmousedown = changeToURL
  likeButtonsAndSuchDiv.appendChild(menuButton)
}


// taken from https://medium.com/@ryan_forrester_/javascript-wait-for-element-to-exist-simple-explanation-1cd8c569e354
function waitForElement(selector, callback) {
    const observer = new MutationObserver((mutations, observer) => {
        const element = document.getElementsByTagName(selector);
        if (element.length > 0) {
            observer.disconnect();
            callback(element[0]);
        }
    });

    observer.observe(document.body, {
        childList: true,
        subtree: true,
    });
}

// Usage
waitForElement('"ytmusic-player-bar"', (element) => {
    console.log('Playbar has been loaded:', element);
    buildButton();
});